POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"admin",
    "password":"123"
}
###
GET http://localhost:5000/
Content-Type: application/json
Authorization: Bearer token

{

}
###
POST http://localhost:5000
Content-Type: application/json
Authorization: Bearer token

{
    "user":"fulano",
    "email":"fulano@gmail.com"
}

###
PUT http://localhost:5000/0
Content-Type: application/json
Authorization: Bearer token

{
    "user":"fulano de tal",
    "email":"fulano@gmail.com"
}

###
DELETE  http://localhost:5000/0
Authorization: Bearer token
Content-Type: application/json

{
    
}